apiVersion: v2
name: portfolio-website
description: Portfolio website
type: application
version: 1.0.0

dependencies:
  - name: base-helm-chart
    version: 0.11.0
    repository: "https://tylerpitcher.github.io/base-helm-chart/"
