image:
  repository: tylerpitcher/portfolio-website
  tag: 1.1.0

deployment:
  replicas: 1
  port: 80
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

env: []

volumes: []

hpa:
  enabled: false

ingress:
  enabled: false
  hosts:
    - www.tylerpitcher.com
    - tylerpitcher.com
  path: /
  tlsSecretName: tylerpitcher-tls
  httpsRedirectMiddleware: https-redirect
